<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>afc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(\[(.+?\])</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\[/[^\]]+\])\s*$</string>
	<key>keyEquivalent</key>
	<string>^~X</string>
	<key>name</key>
	<string>AFC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[(?i:java)\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/(?i:java)\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.java.embedded.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[(?i:ruby)\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/(?i:ruby)\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.ruby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ruby.embedded.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[xml\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/xml\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.xml.embedded.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code\]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.code</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.afc.code</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.code.afc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[/?)([-_a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.afc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.afc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.afc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.afc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.afc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.afc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.afc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.afc</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\B(\*\*)</string>
					<key>end</key>
					<string>(\*\*)</string>
					<key>name</key>
					<string>markup.bold.afc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\B(::)</string>
					<key>end</key>
					<string>(::)</string>
					<key>name</key>
					<string>markup.italic.afc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\B(%%)</string>
					<key>end</key>
					<string>(%%)</string>
					<key>name</key>
					<string>markup.raw.afc</string>
				</dict>
			</array>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.afc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.afc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.afc</string>
		</dict>
		<key>tagStuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.afc</string>
	<key>uuid</key>
	<string>6B54498F-48CF-4CBF-97BE-9A8257944B9E</string>
</dict>
</plist>
